### ISSUE TITLE
Inconsistent UI bugs after update

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#217] opened 2017-03-02 05:33 UTC
Me, @ssand Tahvok are experiencing some issues with the new UI changes merged in with #181:

- ~~Tahvok's wallet starts in fullscreen. Mine and hdw's do not.~~ fixed
- Tahvok and hdw cannot see the new spinner gif while I can.
- ~~Some widgets in the Send Coins dialog are black for me but not for Tahvok and hdw.~~ fixed

**Comment by denravonska** [comment] 2017-03-02 05:39
@skcin Can you have a look at the spinner?

**Comment by Tahvok** [comment] 2017-03-02 12:08
1. The problem is actually in tiling window managers. Thanks to @denravonska potential fix, it seems to be fixed by adding `setWindowFlags(Qt::Dialog);` at line 207


3. The gif is working after a reboot. Weird, but it's working.

**Closed as completed** 2017-03-08 13:15 UTC
Labels: bug
