### ISSUE TITLE
UI: Left alignment of items in toolbar broken when compiling with Qt5 

### ISSUE THREAD

**Issue by skcin** [gridcoin-community/Gridcoin-Research#180] opened 2017-01-08 14:29 UTC
The left alignment of items in the main toolbar of the wallet is broken when installing on arch linux with Qt5. I believe the issue is caused by the missing 'text-align' property of QToolBar in Qt5. So the style sheet does not take effect.

Here is a discussion about it in a Qt-forum:https://forum.qt.io/topic/59049/left-align-qtoolbuttons-in-a-vertical-qtoolbar

**Comment by Tahvok** [comment] 2017-02-01 15:25
I can confirm I have this issue as well.

**Comment by denravonska** [comment] 2017-03-01 12:20
Is this fixed with #181?

**Comment by denravonska** [comment] 2017-03-02 13:44
This turns out to be a little bit tricky. There is no way to change the alignment of QToolButtons other than through a style, which is what happens here. Currently, most (if not all) the KDE styles tweak the way tool buttons are drawn and choose to center them. It IS possible to assign a style proxy which decorates the push buttons with the `_kde_toolButton_alignment` property to left alignment like this:

```
class KdeWorkaroundProxyStyle : public QProxyStyle {
public:
    void polish(QWidget* w) {
        if(qobject_cast<QToolButton*>(w))
            w->setProperty("_kde_toolButton_alignment", Qt::AlignLeft);
    }
};

app.setStyle(new KdeWorkaroundProxyStyle);
```

Not pretty and will probably break in future KDE releases. Given the design volatility of tool buttons we might want to consider a different container for the widgets.

Edit: I suppose we can implement our own toolbar drawing in QProxyStyle::drawControl.

**Comment by skcin** [comment] 2017-03-31 19:25
@denravonska  I think it is possible with QProxyStyle::drawControl but it seems to be rather complicated and not well documented. I get the feeling that it is not worth it. Since we already talked about redesigning the gui why not use  toolbar->setToolButtonStyle(Qt::ToolButtonTextUnderIcon); ? That creates a clean look and we don't have to deal with all that proxy style overhead. The downside is that it needs more vertical space. But if we moved the links for irc, the website an the block explorer to a different place we should be good. The links in the toolbar feel a little bit missplaced anyway. What do you think?

**Comment by denravonska** [comment] 2017-03-31 19:27
@skcin I was thinking the exact same thing with the proxy style and came too the same conclusion. It felt way too hacky and cumbersome.

The tool button style is a great idea. Do you think you can provide a sample so we can get a feel for how it would look? Personally I'd like to move the auxillary links to the Help menu.

**Closed as completed** 2017-05-12 15:18 UTC
