### ISSUE TITLE
Gridcoin Wallet stuck at Block 1010002

### ISSUE THREAD

**Issue by debk3141** [gridcoin-community/Gridcoin-Research#671] opened 2017-10-04 09:54 UTC
MY Wallet is stuck at Block 1010002.
Tried reinstalling and downloading blockchain multiple times nothing helps

**Comment by debk3141** [comment] 2017-10-04 09:56
should have mentioned on version  3.6.2.0

**Comment by tomasbrod** [comment] 2017-10-04 14:50
Duplicate of #572

**Closed as completed** 2017-10-05 04:44 UTC
