### ISSUE TITLE
Discrepancy in the indicated wallet locked/unlocked status 

### ISSUE THREAD

**Issue by an0n7mous3** [gridcoin-community/Gridcoin-Research#1220] opened 2018-07-21 02:05 UTC
When the wallet is unlocked for staking only, and you are in the 'Receive' tab, create a new address. This will prompt to unlock the wallet. After entering one's password and a new address is created, the 'Locked' icon at the bottom of the wallet switches, and a 'Lock wallet' button takes its place. But in reality, the wallet is still locked. 

The icon should not change in this procedure since the wallet is not unlocked

**Comment by chrstphrchvz** [comment] 2018-10-21 16:05
Is this still reproducible? It seems to work in 4.0.0.0. That or I'm not understanding your steps quite right.

Currently when the wallet is unlocked for staking, the padlock icon (now near the top left) changes from locked to unlocked, and the button in the lower left changes from "Unlock wallet" to "Lock wallet". After e.g. creating an address, the padlock icon is still unlocked, the button in lower left still says "Lock Wallet", and the wallet will still show as staking even after waiting a few minutes.

**Comment by jamescowens** [comment] 2019-02-19 15:11
Closing. Can't reproduce.

**Closed as completed by jamescowens** 2019-02-19 15:11 UTC
