### ISSUE TITLE
Wallet offline for hours or longer after every time I stake

### ISSUE THREAD

**Issue by mr-snipes** [gridcoin-community/Gridcoin-Research#870] opened 2018-01-25 19:38 UTC
Every time i stake, the wallet is not in snyc anymore.
If i mouse over the green arrow it shows "offline" Yesterday i had staked and it was stuck in this offline state so i restarted the grc-client and it was fine. 
Today i staked another time (a bit odd but ok) and it is in the offline state again. However it states that i have 8 active connections to the network. 
Assuming that another of these forks had happened and my client did not upgrade itself, i clicked on "upgrade client"  just now.  
The GRCrestarter-app comes with an error-message:
"unable to retrieve upgrade files form azure cluster. try to pen port 1433" 
I dont have any custom settings in the windows-firewall and the upgrades worked to this point, im not sure why this fails. 
My version currently is "v3.7.1.0-unk-317"

cheers

**Comment by mr-snipes** [comment] 2018-01-25 20:04
Ah i did some searching around, you forked around again ;) 
I will try to update not using the broken updater then.
Why do you not learn from your mistakes ? I still cannot see the version-number of the latest client on your website, the updater is broken, i need to google together what other people have figured out about your mishaps with the current upgrade again. Why is there no simple "blink blink, there is a new client-version" at least ? It is one picture-box and a web-query every few hours. IT is not hard to make it a bit more usable for the people who use your wallet.
If i had some "real amount" of GRC vested in this and i would not stake several days, because the client has gone apesh*** after your fork again, i would be annoyed. 
While i do like your project i have to say handling it is a painful hobby sometimes.

**Comment by mr-snipes** [comment] 2018-01-26 18:28
It did not fix itself, im stuck on a fork and even getblockhash 1  is not giving me a blockhash that i can find on gridcoin.network.
How do i force the app to scrap and redownload the whole chain ?  downloadblocks ?

**Comment by tomasbrod** [comment] 2018-01-27 21:25
I wrote the blink blink new version thing few months back, but it was not included in any of the updates, because it was deemed low priority.

**Comment by tomasbrod** [comment] 2018-01-27 21:29
There was one fork. ALL of 3.7.0.0, 3.7.1.0, 3.7.2.0, 3.7.3.0, 3.7.4.0, 3.7.5.0 and even 3.6.13 and 3.6.14 are compatible with "block v9" fork. 3.7.5 just crashes less.
To assure you: you will NOT LOOSE coins by FORKs, only by sending them somewhere.

**Comment by tomasbrod** [comment] 2018-01-27 21:32
You can re-download the whole blockchain by applying a snapshot. You can try your luck by "download blocks" option, but if you have just a basic knowledge of windows file explored, apply the snapshot manually: [snapshot.zip](https://download.gridcoin.us/download/downloadstake/signed/snapshot.zip)

**Comment by mr-snipes** [comment] 2018-01-31 22:31
Thanks, i initiated the download of the whole blockchain, it does not show the micro-earnings i saw on the wrong chain, however it still s stuck offline. But at least this time i was able to find a blockhash to run the reorganize command, i guess i can tell you more in another day or two - it is an EeePc after all.

deleted the dup post

**Comment by mr-snipes** [comment] 2018-02-01 17:02
Thanks, i initiated the download of the whole blockchain, it does not show the micro-earnings i saw on the wrong chain, however it still s stuck offline. But at least this time i was able to find a blockhash to run the reorganize command, i guess i can tell you more in another day or two - it is an EeePc after all.
The wallet crashes when i run the reorg every time.

**Comment by mr-snipes** [comment] 2018-02-03 18:25
Ok, i had let the grc-client download the whole blockchain agian, it failed. 
I tried to use reogranize command, it failed cause the wallet crashed every time. 
I have downloaded your archive of the blockchain, which looked good for a moment. 
Then again i got some tiny stake reward and boom its in offline state again and hanging. 
Diff is currently at 0 so im at a forkie fork and not the main chain im pretty sure.



Should it not be working like that: 


21:45:00
￼
reorganize 7ad36e461d6bec6954a1bdab31c03e4d7a8f3a9336a46ffe396c89d22dc6c000


21:47:49
￼
{
"RollbackChain" : true
}

**Comment by Jojo-A** [comment] 2018-02-08 10:56
Hi,
I think I've got the same problem. I downloaded the latest blockchain snapshot but after a while, almost my whole GRC balance moves to stake and my wallet says "offline" and my rewards do not get confirmed.
My wallet reports this "offline" state since a few days now and I don't get back in sync.

Please let my know, If I can provide additional information about how to solve that.

Thanks

**Comment by tomasbrod** [comment] 2018-02-08 13:17
We identified some issues and new version will be released soon. Wait for the release and then please try again.

**Comment by mr-snipes** [comment] 2018-02-20 16:14
I reinstalled the whole thing on another machine and it worked, removing the peers and all that did not help before. After the fork a few days ago the installation on my new device is also broken. I ran 3 reorganize commands - they were timed well behind the last few days. However it is not coming back to life again.

**Comment by mr-snipes** [comment] 2018-02-21 07:55
Thanks, i will do the chain-dl then again, gonna look at your slack
tonight.

2018-02-21 2:21 GMT+01:00 Josh-D. S. Davis <notifications@github.com>:

**Comment by tomasbrod** [comment] 2018-02-23 22:15
#893 same topic, suggest to close

**Comment by mr-snipes** [comment] 2018-02-23 22:39
Please leave open until resolved, tomasbrod

**Comment by Jojo-A** [comment] 2018-03-09 09:32
Hi,
are there any news regarding this issue? I am running wallet version 3.7.10.0 on an ODROID HC1/XU4 but I am not syncing, stuck on block 1150447, client message: offline.

**Comment by denravonska** [comment] 2018-03-12 02:26
While it should resolve it on its own, you could try a snapshot with 3.7.10.0.

**Comment by Jojo-A** [comment] 2018-03-12 08:22
@denravonska Thank your for the reply! Sadly the approach with the snapshot did not help. But for me, this issue is solved. Basically I just synced with the blockchain from "0" on (so without using a snapshot). Here is what I did exactly: [HERE](https://cryptocurrencytalk.com/topic/98823-not-syncing-client-message-offline/?tab=comments#comment-444529) .  Sorry for the panic and greetings!

**Comment by RoboticMind** [comment] 2018-04-18 01:08
Should this be closed?

**Comment by mr-snipes** [comment] 2018-04-18 06:52
It can be closed, the issue is not persisting in the newer version.

2018-04-18 3:08 GMT+02:00 RoboticMind <notifications@github.com>:

**Closed as completed** 2018-04-23 08:10 UTC
