### ISSUE TITLE
Wrong example address

### ISSUE THREAD

**Issue by sau412** [gridcoin-community/Gridcoin-Research#1350] opened 2018-10-31 12:07 UTC
File: https://github.com/gridcoin-community/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_en.ts
(and every other language file too)
String 2129, 2323, 2431
Contains:
` <source>Enter a Gridcoin address (e.g. G8gZqgY4r2RoEdqYk3QsAqFckyf9pRHN6i)</source>`
There is address with starting G. But actual gridcoin addresses should start from S or R.

**Comment by jamescowens** [comment] 2018-10-31 14:42
Too much copied directly from Bitcoin... he he.

**Comment by dc7dgrid** [comment] 2018-11-05 21:54
It's an old address vom Gridcoin Classic.
Already noted at #1238

**Comment by denravonska** [comment] 2018-12-05 20:19
Closing as duplicate of #1238.

**Closed as completed by denravonska** 2018-12-05 20:19 UTC
