### ISSUE TITLE
Regression: Spacing of Favourites and Receive Tabs do not stretch to the width of the window.

### ISSUE THREAD

**Issue by nathanielcwm** [gridcoin-community/Gridcoin-Research#2256] opened 2021-08-02 05:08 UTC
# Bug Report

**Current behavior**
The Favourites and Receive tabs currently don't stretch to the width of the window.

**Expected behavior**
It stretches to take up the width of the window, like it did on the old UI.

**Steps to reproduce:**
Maximise Gridcoin window on a monitor of 1080p resolution (it would likely be worse on a higher resolution monitor without scaling, but I'm testing on a 1080p screen)

**Screenshots**
![image](https://user-images.githubusercontent.com/22572406/127806685-1d56db47-3b3a-4dec-95ff-84291828f875.png)
![image](https://user-images.githubusercontent.com/22572406/127806689-c6d43c9b-ad0a-4048-8b42-196b041abb8d.png)
Transactions page stretches as expected:
![image](https://user-images.githubusercontent.com/22572406/127806694-9c6d83a2-9de5-4da7-8576-076923b64065.png)

Spacing is less of an issue on a 4:3 monitor:
![image](https://user-images.githubusercontent.com/22572406/127806735-6f4be403-e9ed-4fa6-a560-9f2aee3edcd2.png)

The old UI had no issues:
![image](https://user-images.githubusercontent.com/22572406/127807041-73737350-0aa6-4727-ab38-1c995fd692b1.png)
![image](https://user-images.githubusercontent.com/22572406/127807055-ff25cce3-e981-4ed4-9f50-46152b28020d.png)

**Gridcoin version**
5.3.2

**Machine specs**
- OS: Windows 10 21H1

**Comment by cyrossignol** [comment] 2021-08-02 22:27
@nathanielcwm The spacing is supposed to improve readability by reducing unnecessary eye travel. See https://github.com/gridcoin-community/Gridcoin-Research/issues/2121#issuecomment-858249736.

The transaction history table is an exception because it may actually contain enough information to fill the whole screen for some wallets.

In any case, we may redesign these pages in the future. The flat tables probably aren't the most useful way to organize that data.

**Comment by jamescowens** [comment] 2021-08-03 14:51
I am closing this as it is functionality as intended.

**Closed as completed by jamescowens** 2021-08-03 14:51 UTC
Labels: bug, gui
