### ISSUE TITLE
Accented letters in default data path

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#1470] opened 2019-05-22 11:56 UTC
v4.0.4.0-g4a64ab854 on Windows 10 user Javierf on discord
complained that wallet does not work on his system, because the home directory has accented letters in the path. "Client can't append anything to block file (but can read it)".
After overriding the path in the config file (which is unsupported) the wallet crashes with exception when configuration button is clicked.

**Comment by denravonska** [comment] 2019-05-22 11:58
Related? #277

**Comment by MaeseF** [comment] 2019-05-22 12:05
![image](https://user-images.githubusercontent.com/50913384/58173060-9cdc4580-7c9a-11e9-96bc-3ffac199f331.png)

**Comment by MaeseF** [comment] 2019-05-22 12:05
When you click in "Configuration", it dumps. Is all about the same...

**Comment by tomasbrod** [comment] 2019-05-22 12:20
I was searching for accents and path keywords and i missed 277.

**Comment by jamescowens** [comment] 2019-05-22 16:02
#277 is almost certainly it.

**Comment by jamescowens** [comment] 2019-05-22 16:18
I used boost filesystem stuff in the scraper but it needs to be retrofitted elsewhere...

**Comment by jamescowens** [comment] 2019-05-22 16:46
The steemit post of this shows this is a regression, and this worked before 4.0.3.0?

**Comment by MaeseF** [comment] 2019-05-22 18:59
Yes,working fine up to 4.0.2.
Not working in both 4.0.3 and 4.0.4

**Comment by jamescowens** [comment] 2019-05-26 05:27
This was my fault. I messed up the localization a little in the scraper. I am testing a fix on my local branch and will push a PR to development tomorrow.

**Comment by jamescowens** [comment] 2019-05-29 05:49
Looks like this fixed it. Closing.

**Closed as completed by jamescowens** 2019-05-29 05:49 UTC
Labels: bug

**Comment by jamescowens** [comment] 2019-10-19 20:52
This is done.
