### ISSUE TITLE
Raspberry Pi crash

### ISSUE THREAD

**Issue by Scalextrix** [gridcoin-community/Gridcoin-Research#202] opened 2017-01-29 12:32 UTC
I have been running a self compiled version of 3..5.8.5 on a raspberry pi 3, os raspian-lite, occasionally when I SSH in gridcoinresearchd is no longer running.  I created a systemd service to auto-restart on failure and this has cured the symptom, but I wanted to report here the last lines of the debug.log for a potential fix:

```
Signing Block for cpid db3cf00a057e85fa2d8fa41cebca423c and blockhash dd6c88fbbafba6dd64c45468b0a48d5669f2db9e1a8ea6a579447ec3ad639f23 with sig MEQCIBVUh17EHOs2jCYHzJsBJWAu50EBcChCn4aHGI0wo31UAiBPC8u1S4ad6mVc2JWoc1TxNb4YfSmXLS9MUC$
01/28/17 14:21:16
Signing Block for cpid db3cf00a057e85fa2d8fa41cebca423c and blockhash dd6c88fbbafba6dd64c45468b0a48d5669f2db9e1a8ea6a579447ec3ad639f23 with sig MEUCIQDbhDBUl1ZQi6k8RrtxZ5lInroZ/CUS6PepB9qz93eIxAIgKF+8IRE+EIXA33KFgNuHVcsS4hJo+kI+do$
01/28/17 14:21:18 * Received block c2a74b3343836adf726326031ae6629d34d9e41762a6d381ab10ee2ad74126a1;  Operation ProcessBlock_checkblock_researcher_doublecheck, ComputedAccrual 9.984375, StakeHeight 802797.000000, RABlockSpan 1776.$
01/28/17 14:21:18 -{CheckStakeKernelHashV3::INFO::} PaymentAge 170400.000000, BitsAge 3295.842534, Magnitude 24.000000, Coin_Age 973072.000000, RSAWeight 24.000000
01/28/17 14:21:18 {CheckStakeKernelHashV3::INFO:::: RSA_WEIGHT 24.000000, TimeBlockFrom 1484640192.000000, PrevnTime 1484640192.000000, PrevOutHash dbaf5bcee56604d363f3be74d44ed6d2164a94df34feff92159d41edbcecc7ab, PrevOut 1.000000$
01/28/17 14:21:21 ping timeout: 1200.007183s
01/28/17 14:22:23  Operation ConnectBlock_checkblock_researcher, ComputedAccrual 9.984375, StakeHeight 802797.000000, RABlockSpan 1776.000000, HistoryHeight801021.000000, AccrualAge 1.972222, AvgMag 22.500000, MagUnit 0.225000, PP$
01/28/17 14:22:23 Stake Reward of 10.072501 , DPOR PAID 0.000000     Operation connectblock_researcher, ComputedAccrual 9.984375, StakeHeight 802798.000000, RABlockSpan 1777.000000, HistoryHeight801021.000000, AccrualAge 1.972222,$
01/28/17 14:22:23
[DoTallyRA_START] {SBC} SetBestChain: new best=c2a74b3343836adf7263  height=802798  trust=3275838333972824660711873320762369734724920483558585417587747496401915111063  blocktrust=98303832610  date=01/28/17 14:21:04
01/28/17 14:22:23 {ACC}{PB}: ACC;
01/28/17 14:22:23  {SVC}
Signing Block for cpid db3cf00a057e85fa2d8fa41cebca423c and blockhash dd6c88fbbafba6dd64c45468b0a48d5669f2db9e1a8ea6a579447ec3ad639f23 with sig MEUCIQD3owPtgtzqqgJvaoniHEyWoQdwuZcZKgG9wSboYia3PQIgKuGnu0J/jTyLFngwT5T2Aa2Tqf0rBRxgbQ$
AppInit
```

**Comment by denravonska** [comment] 2017-01-29 12:35
Interesting, it seems to just vanish. Can you try to launch the client in a screen to see if you get an assert line when it ends?

**Comment by Scalextrix** [comment] 2017-01-29 12:39
Do you mean run it from a dektop environment?  It might run for 5 days before the crash, with the systemd service I was monitoring jounalctl to see when it restarted, but I had the issue that the debug.log was wiped.

**Comment by denravonska** [comment] 2017-01-29 13:04
I meant run gridcoinresearchd from inside a screen session after you have ssh:ed to the box. To keep it running after logging out. I don't think debug.log catches messages written to stderr (but don't quote me on that) so I think we miss the crash message.

**Comment by Scalextrix** [comment] 2017-01-29 14:17
OK Linux novice, I just looked up screen and am installing it now

**Comment by denravonska** [comment] 2017-01-29 19:42
Did you get it running? I'll hook it up to my Pi3 as well.

**Comment by Scalextrix** [comment] 2017-01-29 19:58
Yes gridcoinresearchd is running in a screen session, I screwed it up the first time but its ok now.

**Comment by denravonska** [comment] 2017-01-29 19:59
Oh sweet. I'll try to get mine going (without signing) anyway to increase the crash odds.

**Comment by Peppernrino** [comment] 2017-01-29 22:50
@Scalextrix : you feel like sharing how you accomplished your systemd auto-restart with me? it would help to have in the AutoNode script as a failsafe. i have been screwing with upstart, and init.d, and most things i do get reset upon restart, or just don't work... any insight would be helpful. :)

a couple of days ago, i went to upgrade the wallet and my node was also down.

**Comment by Scalextrix** [comment] 2017-01-29 23:55
Sure no worries @Peppernrino its late here now I will update this tomorrow

**Comment by Scalextrix** [comment] 2017-01-30 07:50
@Peppernrino assuming you have gridcoinresearchd installed in `/usr/bin` then this is my method:

pi@raspberrypi:~ $ `gridcoinresearchd stop`

pi@raspberrypi:~ $ `cd /etc/systemd/system`

pi@raspberrypi:~ $ `sudo nano gridcoinresearchd.service`

Enter the following

```
[Unit]
Description=Gridcoin daemon services
After=tlp-init.service

[Service]
Type=simple
RemainAfterExit=yes
ExecStart=/usr/bin/gridcoinresearchd   
Restart=always
RestartSec=60
User=pi

[Install]
WantedBy=multi-user.target
```


CTRL+X, Y and Enter

pi@raspberrypi:~ $ `systemctl enable gridcoinresearchd.service`

pi@raspberrypi:~ $ `systemctl start gridcoinresearchd.service`

pi@raspberrypi:~ $ `systemctl status gridcoinresearchd.service`

Should output something like:

? gridcoinresearchd.service - Gridcoin daemon services
   Loaded: loaded (/lib/systemd/system/gridcoinresearchd.service; enabled)
   Active: active (exited) since Sat 2016-12-10 16:22:58 GMT; 20h ago
  Process: 409 ExecStart=/usr/bin/gridcoinresearchd (code=exited, status=0/SUCCESS)
 Main PID: 409 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/gridcoinresearchd.service
           +-613 /usr/bin/gridcoinresearchd

In `top` you should see gridcoinresearchd running with the process id in the last line (mine is 613). You should be able to restart the Pi without problems and on failure, so far, this has restarted the daemon.  Good luck.

**Comment by denravonska** [comment] 2017-02-01 05:07
Running it now. Is this a duplicate of #166 perhaps?

**Comment by Scalextrix** [comment] 2017-02-01 08:05
Its possible I looked at #166 and could not be sure.  My gridcoinresearchd is still running in screen, Im checking in daily.

**Comment by denravonska** [comment] 2017-02-01 12:35
@Scalextrix Can you check it now? I want to see if has anything to do with superblocks. One was created about an hour ago.

**Comment by Scalextrix** [comment] 2017-02-01 12:48
Its all fine:
```
pi@raspberrypi3:~ $ gridcoinresearchd getinfo
{
    "version" : "v3.5.8.5-g-research",
    "minor_version" : 317,
    "protocolversion" : 180321,
    "walletversion" : 60000,
    "balance" : x.xxxxxxxx,
    "newmint" : 0.00000000,
    "stake" : 0.00000000,
    "blocks" : 806338,
    "timeoffset" : -193,
    "moneysupply" : 385646912.11503559,
    "connections" : 8,
    "proxy" : "",
    "ip" : "x.x.x.x",
    "difficulty" : {
        "proof-of-work" : 8.23948943,
        "proof-of-stake" : 16.45190329
    },
    "testnet" : false,
    "keypoololdest" : 1421788191,
    "keypoolsize" : 101,
    "paytxfee" : 0.00010000,
    "tally" : "",
    "mininput" : 0.00000000,
    "unlocked_until" : 1495701148,
    "errors" : ""

```

**Comment by denravonska** [comment] 2017-02-01 15:29
Crap. Oh well, I'll let mine run in the debugger and we'll see.

**Comment by Peppernrino** [comment] 2017-02-01 21:24
thank you very much, @Scalextrix, i'll get everything together later. :)

**Comment by Scalextrix** [comment] 2017-02-08 17:50
Update guys, its still running after 10 days, I didnt see it run this long before... still have in a screen session

**Comment by denravonska** [comment] 2017-02-08 18:00
@Scalextrix Thanks, keep it running :)

**Comment by Scalextrix** [comment] 2017-02-13 17:07
I restarted my Pi without thinking, #$*\ !!!!  OK we wait some more.

**Comment by Quezacoatl1** [comment] 2017-02-14 17:06
A trigger for shutting down could be downloading the official snapshot and starting from there. At least it used to be for me at a snapshot of about 660k blocks

**Comment by denravonska** [comment] 2017-02-21 16:28
Same as #166?

**Comment by Quezacoatl1** [comment] 2017-02-23 07:19
Maybe...

**Comment by denravonska** [comment] 2017-02-23 07:29
Oh lol, didn't realize I already asked that. Sorry.

**Comment by denravonska** [comment] 2017-02-28 11:57
I just got a crash while in the debugger:

```
Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb)
```

dmesg shows:

```
[591915.153523] Out of memory: Kill process 9622 (gridcoinresearc) score 818 or sacrifice child
[591915.156374] Killed process 9622 (gridcoinresearc) total-vm:968516kB, anon-rss:813588kB, file-rss:0kB
```

If the kernel killed it because we ran out of RAM then there's not much we can do other than trying to lower the RAM footprint. It's also possible that there's a memory leak.

**Comment by Scalextrix** [comment] 2017-02-28 13:02
On my Pi gridcoinresearchd uses less than 50% RAM normally, if something goes wrong then maybe thats the issue.  I found this gist, I wonder if the last point on there is relevant:

https://gist.github.com/laanwj/efe29c7661ce9b6620a7

**Comment by denravonska** [comment] 2017-04-13 14:17
@Scalextrix You've been running the staging branch for a while now? Does it still crash a lot?

**Comment by Scalextrix** [comment] 2017-04-13 16:59
Its been ok recently, lets close this and monitor, agreed?

**Comment by denravonska** [comment] 2017-04-13 17:11
@Quezacoatl1 reports crashes with the staging branch :(

**Comment by Scalextrix** [comment] 2017-04-13 17:15
Oh actually Im not on the staging branch I dont think... you mean from the PPA, correct?
I compile from source.

**Comment by denravonska** [comment] 2017-04-13 17:15
@Scalextrix Which branch do you use? :)

**Comment by Scalextrix** [comment] 2017-04-13 17:30
Master branch, I just do a git pull, make clean and then make from there. I reported the last fork so I was one of the first onto .8 when it was released, not touched it since then.  I was fiddling with the Pi yesterday and it was restarted, but systemctl shows it as running for 26 hours since then.

**Comment by denravonska** [comment] 2017-04-29 04:25
I've been running the staging branch on my Pi3 without a crash for 2 weeks now. Should we consider this one fixed even though no targeted fix has been made? The increased stability could be an accidental fix from the reduced memory requirements even though it feels a bit far fetched.

**Comment by Scalextrix** [comment] 2017-04-29 06:02
I agree, we have a method in systemd / systemctl to auto-restart from crash anyway, so really the issue isnt significant.  I updated the systemd settings and its more stable now, I will post those later and then we can close.

**Comment by Scalextrix** [comment] 2017-04-29 16:48
Updated and better functioning systemd service:


```
[Unit]
Description=Gridcoin daemon services
After=tlp-init.service

[Service]
Type=forking
PIDFile=/home/pi/.GridcoinResearch/gridcoinresearch.pid
RemainAfterExit=yes
ExecStart=/usr/bin/gridcoinresearchd
Restart=on-failure
RestartSec=3
User=pi

[Install]
WantedBy=multi-user.target
```

**Comment by denravonska** [comment] 2017-07-01 08:56
Still an issue? By the looks of the original log this might be related to 0a4d34ff3417f450aa8d52da9079b296b549d9ac.

**Comment by iuvbio** [comment] 2018-01-14 02:31
@Scalextrix, I am getting an error using your systemd service file. I can enable the service, but starting it results in this error:
```
● gridcoinresearchd.service - Gridcoin daemon services
   Loaded: loaded (/lib/systemd/system/gridcoinresearchd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2018-01-14 03:15:57 CET; 1s ago
  Process: 1272 ExecStart=/usr/bin/gridcoinresearchd (code=exited, status=1/FAILURE)

Jan 14 03:15:57 bestgrcnode systemd[1]: gridcoinresearchd.service: Unit entered failed state.
Jan 14 03:15:57 bestgrcnode systemd[1]: gridcoinresearchd.service: Failed with result 'exit-code'.
```

Do you have any idea why?

**Comment by Scalextrix** [comment] 2018-01-14 07:15
on the latest 3.7.3.0 I am also having problems @iuvbio.

If you change 
> Type=forking

to

> Type=simple

then the daemon starts but this is not correct.  We need more info from the devs as to why the daemon isn't forking as it did before v 3.7

**Comment by denravonska** [comment] 2018-01-14 09:34
It seems to be an issue with the latest daemon fix:

> Type=forking will *wait* for the parent process to exit *successfully* before systemd considers the service as having started — this matches the old sysvinit setup quite effectively.

conflicts with:  https://github.com/gridcoin/Gridcoin-Research/blob/master/src/init.cpp#L611
We also need to reenable the db close which was re-commented out at https://github.com/gridcoin/Gridcoin-Research/blob/master/src/init.cpp#L105. That comment is incorrect.

**Comment by denravonska** [comment] 2018-06-13 19:57
Does the client still crash on the Pi?

**Comment by Scalextrix** [comment] 2018-06-13 20:08
Not for me, its solid on my Pi for multiple versions, think this can be closed

**Closed as completed** 2018-06-13 20:08 UTC
Labels: bug
